set SECRET_KEY_BASE=
set SECRET_KEY_AUTH=


set DB_NAME=card_db
set DB_HOSTNAME=localhost
set DB_USER=postgres
set DB_PASSWORD=postgres


set EX_DEP_ARKE_PATH=
set EX_DEP_ARKE_POSTGRES_PATH=
set EX_DEP_ARKE_SERVER_PATH=
set EX_DEP_ARKE_AUTH_PATH=

set MAIL_APIKEY=
set MAIL_DOMAIN=
set MAIL_DEFAULT_SENDER=
